// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHOM0_vMfW25RUmVg0DRqmwKTthq7OwD8',
    appId: '1:416593188326:web:b77d14caee5e09c8953227',
    messagingSenderId: '416593188326',
    projectId: 'hospitalapp-5fa07',
    authDomain: 'hospitalapp-5fa07.firebaseapp.com',
    storageBucket: 'hospitalapp-5fa07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1Lu5Yds3odjejulaxMfVUZ_9bb-Xoa_E',
    appId: '1:416593188326:android:47f09449419b6fd9953227',
    messagingSenderId: '416593188326',
    projectId: 'hospitalapp-5fa07',
    storageBucket: 'hospitalapp-5fa07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq1x3gwvNBVH4faFOJYY2eLVQcj4Ls5XA',
    appId: '1:416593188326:ios:0cc0fb3f3ce6c00a953227',
    messagingSenderId: '416593188326',
    projectId: 'hospitalapp-5fa07',
    storageBucket: 'hospitalapp-5fa07.appspot.com',
    iosBundleId: 'com.example.hospitalapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBq1x3gwvNBVH4faFOJYY2eLVQcj4Ls5XA',
    appId: '1:416593188326:ios:0cc0fb3f3ce6c00a953227',
    messagingSenderId: '416593188326',
    projectId: 'hospitalapp-5fa07',
    storageBucket: 'hospitalapp-5fa07.appspot.com',
    iosBundleId: 'com.example.hospitalapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHOM0_vMfW25RUmVg0DRqmwKTthq7OwD8',
    appId: '1:416593188326:web:7a8974b9d89ac516953227',
    messagingSenderId: '416593188326',
    projectId: 'hospitalapp-5fa07',
    authDomain: 'hospitalapp-5fa07.firebaseapp.com',
    storageBucket: 'hospitalapp-5fa07.appspot.com',
  );
}
